"""Create / refresh Countries/ and Regions/ notes from the `countries` / `regions` of dataset notes.

Usage: python3 _tools/build_geo.py [--check]

Each country note gets an auto-generated block (between the %% auto %% markers) listing, per kind, the
datasets that cover it with their key flags as wikilinks (so they also show up in the graph). Text outside
the block is hand-written and is never touched. New notes start from Templates/Country.md / Region.md.
Countries are assigned to a region via REGION_OF below; unknown names are reported.
--check only reports names that are not in REGION_OF (likely misspellings) without writing.
"""
import collections, glob, os, re, sys

VAULT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(VAULT)
TODAY = "2026-10-07"
PRIORITY = {"Middle East", "Central Asia", "South Asia", "East Asia", "Southeast Asia"}
REGIONS = {
    "Middle East": "Bahrain, Iran, Iraq, Israel, Jordan, Kuwait, Lebanon, Oman, Palestine, Qatar, Saudi Arabia, "
                   "Syria, Turkey, United Arab Emirates, Yemen, Cyprus",
    "North Africa": "Algeria, Egypt, Libya, Morocco, Sudan, Tunisia, Mauritania, Western Sahara",
    "Central Asia": "Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan, Uzbekistan, Afghanistan, Mongolia, "
                    "Azerbaijan, Armenia, Georgia",
    "South Asia": "Bangladesh, Bhutan, India, Maldives, Nepal, Pakistan, Sri Lanka",
    "East Asia": "China, Hong Kong, Japan, Macau, North Korea, South Korea, Taiwan",
    "Southeast Asia": "Brunei, Cambodia, Indonesia, Laos, Malaysia, Myanmar, Philippines, Singapore, Thailand, "
                      "Timor-Leste, Vietnam",
    "Europe": "Albania, Andorra, Austria, Belarus, Belgium, Bosnia and Herzegovina, Bulgaria, Croatia, "
              "Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Iceland, Ireland, "
              "Italy, Kosovo, Latvia, Liechtenstein, Lithuania, Luxembourg, Malta, Moldova, Monaco, Montenegro, "
              "Netherlands, North Macedonia, Norway, Poland, Portugal, Romania, Russia, San Marino, Serbia, "
              "Slovakia, Slovenia, Spain, Sweden, Switzerland, Ukraine, United Kingdom, Vatican City, Scotland, "
              "England, Wales, Northern Ireland, Faroe Islands, Guernsey, Jersey, Isle of Man, Gibraltar",
    "Sub-Saharan Africa": "Angola, Benin, Botswana, Burkina Faso, Burundi, Cameroon, Cape Verde, "
                          "Central African Republic, Chad, Comoros, Côte d'Ivoire, Democratic Republic of the Congo, "
                          "Djibouti, Equatorial Guinea, Eritrea, Eswatini, Ethiopia, Gabon, Gambia, Ghana, Guinea, "
                          "Guinea-Bissau, Kenya, Lesotho, Liberia, Madagascar, Malawi, Mali, Mauritius, Mozambique, "
                          "Namibia, Niger, Nigeria, Republic of the Congo, Rwanda, São Tomé and Príncipe, Senegal, "
                          "Seychelles, Réunion, Sierra Leone, Somalia, South Africa, South Sudan, Tanzania, Togo, Uganda, "
                          "Zambia, Zimbabwe",
    "North America": "Canada, United States, Greenland",
    "Latin America": "Antigua and Barbuda, Argentina, Bahamas, Barbados, Belize, Bolivia, Brazil, Chile, Colombia, "
                     "Costa Rica, Cuba, Dominica, Dominican Republic, Ecuador, El Salvador, Grenada, Guatemala, "
                     "Guyana, Haiti, Honduras, Jamaica, Mexico, Nicaragua, Panama, Paraguay, Peru, Puerto Rico, "
                     "Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines, Suriname, "
                     "Trinidad and Tobago, Uruguay, Venezuela, Anguilla, Sint Maarten, Curaçao, Aruba, Martinique, Guadeloupe, Bermuda, Cayman Islands, "
                     "Montserrat, Falkland Islands, Saint Barthélemy, United States Virgin Islands, "
                     "French Guiana",
    "Oceania": "Australia, Fiji, Kiribati, Marshall Islands, Micronesia, Nauru, New Zealand, Palau, "
               "Papua New Guinea, Samoa, Solomon Islands, Tonga, Tuvalu, Vanuatu, Hawaii, American Samoa, Cook Islands, "
               "French Polynesia, Guam, New Caledonia, Niue, Northern Mariana Islands, Pitcairn, Tokelau, "
               "Wallis and Futuna",
}
REGION_OF = {c.strip(): r for r, cs in REGIONS.items() for c in cs.split(",")}
START, END = "%% auto:start (generated by _tools/build_geo.py; edit outside this block) %%", "%% auto:end %%"


def frontmatter(s):
    return s[4:].split("\n---\n", 1)[0] if s.startswith("---\n") else ""


def prop(fm, key):
    m = re.search(rf"^{key}:\s*['\"]?([^'\"\n]*)", fm, re.M)
    return m.group(1).strip() if m else None


def prop_list(fm, key):
    m = re.search(rf"^{key}:[ \t]*(\[.*\])?[ \t]*\n((?:[ \t]+-.*\n?)*)", fm + "\n", re.M)
    if not m:
        return []
    raw = re.findall(r"\[\[[^\]]+\]\]|[^,\[\]]+", m.group(1)[1:-1]) if m.group(1) else []
    raw += re.findall(r"^[ \t]+-[ \t]*(.+)$", m.group(2), re.M)
    vals = (v.strip().strip("'\"").strip("[]").split("|")[0].strip() for v in raw)
    return [v for v in vals if v]


def flags(d):
    if "food" in d["kind"]:
        f = [("ingredients" if d["has_ingredients"] == "true" else "no ingredients")]
        if d["has_ingredients"] == "true":
            f.append(f"amounts: {d['has_amounts']}")
        f.append(f"cooking: {d['has_cooking_method']}")
        if d["has_nutrition"] == "true":
            f.append("nutrition")
        return ", ".join(f)
    if "case" in d["kind"]:
        return (f"cases: {', '.join(d['case_type']) or '?'} → {', '.join(d['conclusion_type']) or '?'}, "
                f"diet: {d['diet_relevance'] or '?'}")
    return f"body effect: {d['body_effect']}"  # the how is in the dataset note / Datasets.base


def line(d):
    acc = {"true": "accessed", "partial": "partly accessed", "false": "not accessed"}.get(d["accessed"], d["accessed"])
    return f"- [[{d['name']}]] · {d['availability']} · {acc} · {flags(d)}"


def auto_block(ds, heading_level="##"):
    out = [START]
    for kind, title in [("food", "Food & dish datasets"), ("ingredient", "Ingredient datasets"),
                        ("compound", "Compound datasets"), ("case", "Patient case datasets")]:
        sel = [d for d in ds if kind in d["kind"]]
        out += [f"{heading_level} {title} ({len(sel)})"] + ([line(d) for d in sel] or ["- none"]) + [""]
    return "\n".join(out).rstrip() + "\n" + END


def upsert(path, template, fields, block):
    if os.path.exists(path):
        s = open(path).read()
    else:
        s = open(template).read()
        for k, v in fields.items():
            s = re.sub(rf"^{k}:.*$", f"{k}: {v}", s, count=1, flags=re.M)
            s = s.replace("{{" + k + "}}", str(v).strip('"'))
        s = s.replace("updated: YYYY-MM-DD", f"updated: {TODAY}")
    if START in s:
        s = s[: s.index(START)] + block + s[s.index(END) + len(END):]
    else:  # first run: put the block right after the summary callout
        s = re.sub(r"(> \[!summary\][^\n]*\n(?:>[^\n]*\n)*)", lambda m: m.group(1) + "\n" + block + "\n", s, count=1)
    open(path, "w").write(s)


def main():
    datasets = []
    for p in sorted(glob.glob("Datasets/*.md")):
        fm = frontmatter(open(p).read())
        datasets.append(dict(name=os.path.basename(p)[:-3], kind=prop_list(fm, "kind"),
                             countries=prop_list(fm, "countries"), regions=prop_list(fm, "regions"),
                             **{k: prop(fm, k) or "" for k in ("availability", "accessed", "has_ingredients",
                                "has_amounts", "has_cooking_method", "has_nutrition", "body_effect",
                                "body_effect_how", "diet_relevance")},
                             case_type=prop_list(fm, "case_type"), conclusion_type=prop_list(fm, "conclusion_type")))
    by_country, by_region = collections.defaultdict(list), collections.defaultdict(list)
    for d in datasets:
        for c in d["countries"]:
            by_country[c].append(d)
        for r in d["regions"]:
            by_region[r].append(d)
    unknown = sorted(c for c in by_country if c not in REGION_OF)
    if unknown:
        print("countries not in REGION_OF (fix the dataset note or add them):", ", ".join(unknown))
    if "--check" in sys.argv:
        return
    for c, ds in by_country.items():
        r = REGION_OF.get(c)
        upsert(f"Countries/{c}.md", "Templates/Country.md",
               {"country": f'"{c}"', "regions": f'["[[{r}]]"]' if r else "[]",
                "priority_region": str(r in PRIORITY).lower()},
               auto_block(ds).replace(END, "Global resources (no country labels, usable for any country): [[Global]]\n" + END))
    for r in sorted(set(REGIONS) | {"Global"} | set(by_region)):
        members = sorted(c for c in by_country if REGION_OF.get(c) == r)
        country_lines = [f"- [[{c}]]: {len(by_country[c])} datasets" for c in
                         sorted(members, key=lambda c: -len(by_country[c]))]
        block = "\n".join([START, f"## Countries with data ({len(members)})", *(country_lines or ["- none"]), "",
                           auto_block(by_region.get(r, []), "###").replace(START + "\n", "## Datasets labelled with the whole region\n")])
        upsert(f"Regions/{r}.md", "Templates/Region.md",
               {"region": f'"{r}"', "countries": "[" + ", ".join(f'"[[{c}]]"' for c in members) + "]",
                "priority_region": str(r in PRIORITY).lower()}, block)
    print(f"{len(by_country)} country notes, {len(set(REGIONS) | {'Global'} | set(by_region))} region notes written "
          f"from {len(datasets)} datasets")


if __name__ == "__main__":
    main()
